export const SCREENS = {
  LOGIN: 'login',
  REGISTER: 'signUp',
  MY_PROFILE: 'myProfile',
  MY_FOLLOWER_FOLLOWING: 'myFollowerFollowing',
  BUDDY_FOLLOWER_FOLLOWING: 'BuddyFollowerFollowing',
  MY_CHATS: 'myChats',
  BUDDY_PROFILE: 'buddyProfile',
  PROFILE_SETTINGS: 'profileSettings',
  PRIVACY_SETTINGS: 'privacySettings',
  BLOCKED_LIST: 'blockedList',
  TRIPS_LIST: 'tripsList',
  VIEW_MY_TRIP: 'viewMyTrip',
  NOTIFI_SETTTINGS: 'notificationSettings',
  FAQ: 'faqsScreen',
  EDIT_PROFILE: 'editProfile',
  DELETE_STEP1: 'deleteStep1',
  DELETE_STEP2: 'deleteStep2',
  TRIP_REQUESTS: 'tripRequests',
  FRIEND_REQ: 'FriendReq',
};
